# @package _global_
problem:
  PID: f1_l-d_kp_10_269
  prob_name: knapsack
  prob_type: discrete
  opt_goal: maximise
  dimensions: null  # Will be set after loading
  opt_global: null  # Will be set after loading
  capacity: null    # Will be set after loading
  mean_value: null  # Will be set after loading
  mean_weight: null # Will be set after loading
  items_dict: null  # Will be set after loading
  
  # Problem loading
  loader:
    _target_: src.problems.ProblemScripts.load_problem_KP
    filename: f1_l-d_kp_10_269
  
  # Fitness function
  fitness_fn: eval_noisy_kp_v2
  fitness_params:
    items_dict: null  # Will be set after problem loading
    capacity: null    # Will be set after problem loading
    noise_intensity: 0
  
  # Attributes and weights
  attr_function: binary_attribute
  weights: [1.0] 