# ==============================
# Run information
# ==============================

experiment_name: "single objective jump"

# ==============================
# Run Configuration
# ==============================
run:
  max_gens: 100
  eval_limit: 10000
  use_noise_dependent_eval_limit: true
  eval_limit_for_noise:
    "0": 38392
    "1": 38392
    "2": 41066
    "3": 44477
    "4": 50728
    "5": 56851
    "6": 64079
    "7": 70736
    "8": 790344
    "9": 86078
    "10": 93638
  seed: 1
  num_runs: 50
  parallel: true

# ==============================
# MLflow Configuration
# ==============================
mlflow:
  tracking_uri: "data/mlruns"

# ==============================
# Hydra Configuration
# ==============================
hydra:
  run:
    dir: "data/outputs"

# hydra:
#   mode: MULTIRUN
#   sweeper:
#     params:
#       # algo.pop_size: 100,200,300
#       problem.fitness_params.noise_intensity: 0
#   sweep:
#     dir: data/outputs

# ==============================
# Algorithm Configuration
# ==============================
algo:
  name: OnePlusOneEA
  type: MuPlusLamdaEA
  use_dynamic_pop_size: false
  static_indpb: 0.01
  use_dynamic_mutation: false
  
  # Dynamic mutation rate function
  indpb_fn:
    _target_: run_helpers.inverse_n_mut_rate
    n_items: null  # Will be resolved after problem loading
    noise: 0  # 
  
  # Algorithm initialization parameters
  init_args:
    _target_: src.algorithms.Algorithms.MuPlusLamdaEA
    mu: 1
    lam: 1
    mutate_function: "probFlipBit"
    mutate_params:
      indpb: null  # Will be resolved dynamically

# ==============================
# Problem Configuration
# ==============================
problem:
  PID: null
  prob_name: jump
  prob_type: discrete
  opt_goal: maximise
  dimensions: 100        # bit-string length
  opt_global: 100        # known optimum
  capacity: 0            # Not applicable for OneMax, set to 0
  mean_value: 50.0       # Not applicable for OneMax, set to middle value
  mean_weight: 0.5       # Not applicable for OneMax, set to middle value
  
  # Problem loading - OneMax doesn't need a loader, dimensions are fixed
  loader: null
  
  # Fitness function
  fitness_fn: jump_fitness
  fitness_params:
    noise_intensity: 0
    gap_size: 10
  
  # Attributes and weights
  attr_function: binary_attribute
  weights: [1.0] 