experiment_name: "test02_KP_LON"

# ==============================
# Run Configuration
# ==============================
run:
  num_runs: 3000  # how many basin-hops (seeds) to aggregate
  seed: 1
  parallel: true
  num_workers: 50

# ==============================
# MLflow Configuration
# ==============================
mlflow:
  tracking_uri: "data/mlruns"

# ==============================
# Hydra Configuration
# ==============================
hydra:
  run:
    dir: "data/outputs"

# ==============================
# LON Configuration
# ==============================
lon:
  name: BinaryLON
  pert_attempts: 1500
  n_flips_mut: 1
  n_flips_pert: 2
  compression_accs: ["None", 0, 1, 2, 5, 10]

# ==============================
# Problem Configuration
# ==============================
problem:
  prob_name: knapsack
  prob_type: discrete
  opt_goal: maximise
  dimensions: null   # set after loader
  opt_global: null   # set after loader
  capacity: null
  mean_value: null
  mean_weight: null
  items_dict: null

  # Instance loader (like your EA config)
  loader:
    _target_: src.problems.ProblemScripts.load_problem_KP
    filename: f1_l-d_kp_10_269

  # Fitness function used for LONs (deterministic KP by default)
  fitness_fn: eval_ind_kp
  fitness_params:
    items_dict: null   # set after loader
    capacity: null     # set after loader
    penalty: 1

  # Attribute generator and fitness direction
  attr_function: binary_attribute
  weights: [1.0]