# @package _global_
problem:
  PID: f1_l-d_kp_10_269
  prob_name: knapsack
  prob_type: discrete
  opt_goal: maximise
  dimensions: null
  opt_global: null
  capacity: null
  mean_value: null
  mean_weight: null
  items_dict: null

  loader:
    _target_: src.problems.ProblemScripts.load_problem_KP
    filename: f1_l-d_kp_10_269

  fitness_fn: eval_noisy_kp_v1_mo
  fitness_params:
    items_dict: null
    capacity: null
    noise_intensity: 0
    penalty: 0

  attr_function: binary_attribute
  weights: [1.0, -1.0]
  ref_point: [0, 269]
