# @package _global_
# BASE SETTINGS
defaults:
  - /defaults/mlflow
  - _self_   # ensures overrides below take precedence

# OVERRIDES
# none

# EXPERIMENT SETTINGS
experiment_name: "config_test_2"

hydra:
  mode: MULTIRUN
  sweeper: # sweep through various combinations of parameters
    params:
      +defaults/run: run_budget_onemax
      +defaults/problems: onemax100_1qbitwise
      +defaults/algos: mup1ea,1p1ea,umda
      problem.fitness_params.noise_intensity: 0,1,2,3,4,5
  sweep:
    dir: data/outputs
